/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.1.1/userguide/building_java_projects.html
 */

plugins {
    application

    id("com.github.ben-manes.versions") version "0.51.0"
    id("com.dorongold.task-tree") version "4.0.0"
    kotlin("jvm") version "2.0.20"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val KOTEST_VERSION = "5.9.1"

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    implementation("javax.vecmath:vecmath:1.5.2")
    implementation("me.saharnooby:qoi-java:1.2.1")
    implementation("org.sejda.imageio:webp-imageio:0.1.6")

    testImplementation("org.junit.jupiter:junit-jupiter:5.11.4")
}

application {
    // Define the main class for the application.
    mainClass.set("com.marginallyclever.showthr.ShowTHR")
    group = "com.marginallyclever"
    version = "0.0.1-SNAPSHOT"
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}

kotlin {
//    jvmToolchain {
//        languageVersion.set(JavaLanguageVersion.of(<MAJOR_JDK_VERSION>))
//    }
//    // Or shorter:
//    jvmToolchain(<MAJOR_JDK_VERSION>)
    // For example:
    jvmToolchain(21)
}